### PR TITLE
Use flatmap instead of map and reduce.

### PR DESCRIPTION
**Pull request by marcushanses**

### CODE REVIEW

**Review by robinnedergard — CHANGES_REQUESTED** [review]
upgrade target version (in tsconfig.test.json) to es version with flatMap:
```
{
	"compilerOptions": {
		"target": "es6",
```

**Comment by marcushanses** [comment]
> upgrade target version (in tsconfig.test.json) from es6 to es version containing the flatMap function:
> 
> ```
> {
> 	"compilerOptions": {
> 		"target": "es6",
> ```

This will be done in a separate pr and this pr will be merged after.

**Comment by Magnus93** [comment]
> > upgrade target version (in tsconfig.test.json) from es6 to es version containing the flatMap function:
> > ```
> > {
> > 	"compilerOptions": {
> > 		"target": "es6",
> > ```
> 
> This will be done in a separate pr and this pr will be merged after.

Add a checkbox for the PR that needs to be merged first and rebase on that PR.

**Review by robinnedergard — APPROVED** [review]
No change to target need, good to go!

**Review by fredrikbryntesson — APPROVED** [review]

**Pull request merged**
